// Code generated by the multiversx-sc build system. DO NOT EDIT.

// Configuration that works with rustc < 1.73.0.
// If you use rustc >= 1.73.0, you can use the more modern configuration below.
#[allow(deprecated)]
pub use multiversx_sc_wasm_adapter::*;
